#!/bin/sh

xrandr --dpi 220

xwallpaper --zoom ~/Pictures/wallpapers/ghibliesque.jpg &

pipewire &

monarr &

autostart="mpd xcompmgr dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

