#!/bin/sh

xrandr --auto &
xrandr --dpi 220 &

dwmblocks &

rbg &

pipewire &

trimonarr &

autostart="mpd xcompmgr dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

pkill -SIGUSR1 dwmblocks
