#!/bin/sh

xrandr --dpi 220

xwallpaper --zoom $HOME/.local/share/bg/papes/scififuture/toruscutaway.jpg &

pipewire &

monarr &

autostart="mpd xcompmgr dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

